### ISSUE TITLE
join() is very slow

### ISSUE THREAD

**Issue by msharp1** [chummersone/pywavfile#24]
Hi,
I had a try with `wavfile.join()` to interleave two mono wav files, 33MB each. After a few minutes I interrupted the process and only wrote about 24MB. I was expecting it to be faster, aren't you ?
Cheers

**Comment by msharp1** [comment]
Thank you for the answer. I saw some comments here and there that numpy could help. But that's not a trivial dependency... Anyway as it's on your todo feel free to close this issue.

**Comment by chummersone** [comment]
Yes I'm sure NumPy could simplify and speed up a number of operations. But, as you say, it's not a small dependency. I prefer to minimise dependencies as much as is sensible, and in this case I don't think it's worthwhile.

**Comment by chummersone** [comment]
BTW I will keep the issue open as a reminder to me to fix it.

**Comment by chummersone** [comment]
Turns out that there were lots of unnecessary calls to `_io.BufferedWriter.seek`, as the package was continuously updating the chunk headers. Removing those calls and deferring the chunk header updates to file close has significantly reduced the processing time (by around 40% on my machine). Closing this for now, as further optimisation is likely to yield more modest savings for significantly greater effort.
